### ISSUE TITLE
Trigger from hibernation

### ISSUE THREAD

**Issue by pgorsuchkahoot** [macadmins/escrow-buddy#14]
I have recently deployed EB to some systems and testing works totally, awesomely as expected.  That said, I am impatient and would like to get these invalid/missing PRK resolved a bit quicker but without being too abusive on my clients.  

I was playing with adjusting the power management settings to drop a system into Hibernation instead of Sleep (ex. `pmset -a hibernatemode 25`), paired with a Jamf Config Policy to require unlocking FV when coming out of that state, and then restoring normal sleep mode when the PRK is properly in escrow.  

The latter part (Jamf stuff) works as anticipated but it seems that EB doesn't trigger during this flow.  Can you confirm this is as expected (i.e. no trigger from exiting Hibernation) and, if it is possible, point me toward how this can be enabled?

**Comment by homebysix** [comment]
Waking from hibernation doesn't trigger all the authorization mechanisms associated with the macOS loginwindow the same way that startup or login does, therefore Escrow Buddy cannot be triggered by wake (from either sleep or hibernation) events. This is a design choice of macOS, unrelated to Escrow Buddy, and so is expected behavior.

I understand the desire to get the invalid/missing PRKs resolved quickly, though, so I might suggest some using some gentle reminders to get users to log out, like the options outlined here: https://www.elliotjordan.com/posts/escrow-buddy-reminders/
