### ISSUE TITLE
Support for disk encryption policy

### ISSUE THREAD

**Issue by aemeuse** [macadmins/escrow-buddy#3]
**Summary**

Our organization currently uses Jamf as our MDM provider, and we enforce key escrow by [using a policy](https://docs.jamf.com/10.24.1/jamf-pro/administrator-guide/Deploying_Disk_Encryption_Configurations.html) rather than a configuration profile. Is there any plan to support this method of key escrow?

**Environment**

- Escrow Buddy version: 1.0.0
- macOS version: Ventura 13.4

**Additional Context**

We tried out escrow buddy with just the disk encryption policy alongside it, and the logs said `ERROR: No MDM profile for enforcing FileVault escrow is present.`

Thanks!

**Comment by homebysix** [comment]
Hi @aemeuse — Escrow Buddy should work for organizations that enable FileVault using a Jamf policy instead of a profile. The one minor change you may need to make is to start deploying an _escrow_ profile. This profile would not enforce enablement of FileVault (your existing policy would continue doing that) but would ensure that any new recovery keys that are generated post-enablement find their way to Jamf.

![Screenshot 2023-08-07 at 2 07 11 PM](https://github.com/macadmins/escrow-buddy/assets/7801391/d84788c6-c4c9-4a5f-8ff7-6d763a1e625d)

In the profile editor interface shown above, just ensure the "Include" toggle is ON for the escrow payload and OFF for the enablement payload.
